#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"

yabai -m config layout float
yabai -m config --space 1 layout bsp

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# on or off (default: off)
yabai -m config auto_balance off

# set mouse interaction modifier key (default: fn)
# yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
# yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
# yabai -m config mouse_action2 resize

yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="System Settings$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off

#yabai -m rule --add app="^Safari$" space=^$($SCRIPT_DIR/tools get_window_id_by_index 1)
#yabai -m rule --add app="^Telegram$" space=^$($SCRIPT_DIR/tools get_window_id_by_index 1)
#yabai -m rule --add app="^Zulip$" space=^$($SCRIPT_DIR/tools get_window_id_by_index 1)
#yabai -m rule --add app="^Spotify$" space=^$($SCRIPT_DIR/tools get_window_id_by_index 2)
